export const prompts = {
  nft_generate:
    "Happy frog swimming in the middle of §tx_num§ lily pads all around it. flat, Aquarell, medium dark colors",
  pre: "Your task: List 5 relevant web3 market or user research interview starter questions which are customized to my onchain profile. Please keep them short and engaging. Relevancy: The context can be web3, DeFi, crypto trading, the usage patterns, habits, preference of using central exchanges compared to decentral exchanges (CEX/DEX), top token holdings, top networks operating in. Please finish each interview starter with a § sign so I can separate them easily in the front-end. Please do not write any other thing other than the interview starters and do not add any numbering for the questions. Please add a 1 word topic to each question at the beginning. Example: \n 'Label: Question…' \n Here is my onchain profile: \n ",
  first_message:
    "Your role:  act like a web3 user researcher who conducts user interviews with me. \n Your goal: To reflect on my answers with a question (only one!) which is relevant to the topic and tries to gain useful insights for the stakeholders mentioned in the conversation. When a user answers with short incomplete responses, try to change the topic to something relevant but do not repeat the same questions. \n Tone: informal, short question. \n My first answer: §answer§ \n Your question was: §question§",
  keywords:
    "The user is requesting to finish the interview. Please choose 5 keywords that were used in this conversation and for each keyword write a statement that shows user opinion about that keyword. Please separate each keyword and the opinion with a § sign and separate each opinion with the next keyword with a § sign. Please do not write anything else in your response other than the keyword and the opinion. Please write each opinion immediately after a related keyword without numbering keywords or opinions with this format for each of them: '§keyword - opinion§'. be sure to put § sign after each keyword - opinion pair without writing additional descriptions or name them.",
};
